<?php
// This is a random PHP script generated by a language model

$name = "John";
$age = 30;

function greet($name) {
    echo "Hello, $name!";
}

greet("World");

if ($age >= 18) {
    echo "You are old enough to vote.";
} else {
    echo "You are not old enough to vote.";
}
?>