<?php
// Random PHP code generated by AI Assistant

// Get the current date and time
$date = new DateTime();
$currentTime = $date->getTimestamp();

// Check if it is a leap year
if ($date->format('L') == 1) {
    $leapYear = true;
} else {
    $leapYear = false;
}

// Calculate the number of days in the month
$daysInMonth = cal_days_in_month(CAL_GREGORIAN, $date->format('m'), $date->format('Y'));

// Check if it is a weekend day
if ($date->format('N') >= 6) {
    $weekendDay = true;
} else {
    $weekendDay = false;
}

// Get the name of the month
$monthName = $date->format('F');

// Get the name of the day
$dayName = $date->format('l');

// Calculate the number of seconds in the current time
$secondsInCurrentTime = $currentTime - strtotime("00:00:00");

// Print the result
echo "Today is {$monthName} {$date->format('d')}, {$date->format('Y')}. It is currently {$date->format('h:i:s A')}.\n";
echo "It is a {$dayName} and it is a {$leapYear ? 'leap' : 'non-leap'} year.\n";
echo "There are {$daysInMonth} days in this month.\n";
echo "The current time is {$secondsInCurrentTime} seconds since midnight.\n";
?>